baseURL = 'https://jdkjjasd.github.io/miaosun/'
languageCode = 'en-us'
title = 'Miao Sun'
theme = "Anatole" 

[params]
title = "Miao Sun"
author = "Miao Sun"
description = "Jr. softwear engineer"
profilePicture = "images/profile.jpg"
contentratio = 0.7
displayMode = "dark"
mainSections = []


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:msuen0528@gmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://jdkjjasd.github.io/miaosun/"




[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
